name: Fork Sync

on:
  schedule:
    - cron: '0 0 * * *' # every day
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.9.0
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          owner: Mintimate
          base: main
          head: main
