name: Fork Sync

on:
  schedule:
    - cron: '0 0 * * *' # every day
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    steps:
      - name: sync_main
        uses: tgymnich/fork-sync@v1.9.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: Mintimate
          base: main
          head: main
